version: "3.3"
services:
  core:
    image: dyde/opre-software-core
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - opre-software:/app/projects
  gui:
    image: dyde/opre-software-gui
    ports:
      - "80:80"
volumes:
  opre-software: